baseurl = "https://blog.josephcbradley.co.uk/"
languageCode = "en-gb"
title = "Joseph Bradley"
theme = "hyde"
enableEmoji = true
disqusShortname = "blog-josephcbradley-co-uk"

[permalinks]
  post = "/posts/:slug/"


[Menus]
  main = [
      {Name = "About", URL = "/about"},
      {Name = "Posts", URL = "/post"},
      {Name = "Subscribe", URL = "/subscribe"},
  ]

[params]
avatar = "img/grapes.svg"
themeColor = "theme-base-09"
layoutReverse = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
