baseurl = "/"
languageCode = "en-gb"
title = "Hugo Grapes Theme"
theme = "hyde"
enableEmoji = true

[permalinks]
  post = "/posts/:slug/"


[Menus]
  main = [
      {Name = "About", URL = "/about"},
      {Name = "Posts", URL = "/post"},
  ]

[params]
avatar = "img/grapes.svg"
themeColor = "theme-base-09"
layoutReverse = true
